apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-block-storage
parameters:
  encrypted: "false"
  kmsKeyId: ""
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
