kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: efs-file-storage
provisioner: openshift.org/aws-efs
parameters:
  gidMin: "40000"
  gidMax: "50000"
